name:                MazeGen



dependencies:
- base >= 4.7 && < 5
- containers
- random
- gloss
- array
- QuickCheck
- aeson
- text
- safe
- bytestring
- time
- disjoint-set

library:
  source-dirs: src

executables:
  MazeGen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MazeGen